### ISSUE TITLE
 wrong static-ness for SootMethodRefImpl when Building the CallGraph with Spark framework

### ISSUE THREAD

**Issue by achabdo** [Sable/soot#1019]
I have a probleme when building the call graph using SPARK for the apache xalan jar, I get this error :
soot.ResolutionFailedException: Resolved <org.apache.xalan.xsltc.dom.KeyIndex: org.apache.xalan.xsltc.DOMEnhancedForDTM access$100(org.apache.xalan.xsltc.dom.KeyIndex)> to <org.apache.xalan.xsltc.dom.KeyIndex: org.apache.xalan.xsltc.DOMEnhancedForDTM access$100(org.apache.xalan.xsltc.dom.KeyIndex)> which has wrong static-ness
	at soot.SootMethodRefImpl.checkStatic(SootMethodRefImpl.java:114)
	at soot.SootMethodRefImpl.resolve(SootMethodRefImpl.java:128)
	at soot.SootMethodRefImpl.resolve(SootMethodRefImpl.java:109)
	at soot.jimple.internal.AbstractInvokeExpr.getMethod(AbstractInvokeExpr.java:54)
	at soot.jimple.toolkits.callgraph.OnFlyCallGraphBuilder.findReceivers(OnFlyCallGraphBuilder.java:552)
	at soot.jimple.toolkits.callgraph.OnFlyCallGraphBuilder.processNewMethod(OnFlyCallGraphBuilder.java:532)
	at soot.jimple.toolkits.callgraph.OnFlyCallGraphBuilder.processReachables(OnFlyCallGraphBuilder.java:425)
	at soot.jimple.spark.solver.OnFlyCallGraph.build(OnFlyCallGraph.java:55)
	at soot.jimple.spark.builder.ContextInsensitiveBuilder.build(ContextInsensitiveBuilder.java:84)
	at soot.jimple.spark.SparkTransformer.internalTransform(SparkTransformer.java:83)
	at soot.SceneTransformer.transform(SceneTransformer.java:39)

**Comment by mbenz89** [comment]
We have an `ignore-wrong-staticness-option` that might help.

@StevenArzt Can you shed some light on why these staticness errors occur in the first place? I saw you implemented some code (`MethodStaticnessCorrector`) that changes the staticness of methods were possible in some cases.

**Comment by achabdo** [comment]
It 's not working when i use  Options.v().setPhaseOption("jb.tr", "ignore-wrong-staticness:true");

**Comment by StevenArzt** [comment]
Some input programs are not fully compliant with standards. Apparently, some execution environments, most notably Android, are perfectly fine with calling static methods as instance methods. At least, the apps that contain such code seem to work just fine on a real device. I'm not sure where such code comes from in the first place, because compilers should not mess up invocation opcodes. Maybe some developers use some buggy instrumentation framework or the like, but that's guesswork.

For program analysis, having the wrong invocation opcode is in any case, because we rely on specific models for mapping e.g., abstractions on base objects from call site to callee. Therefore, I added the option to try and fix those staticness errors during the import. Of course, this is a best-effort approach. We might fail, but usually, we are able to get at least something we can then analyze (instead of just failing on the whole input program).

**Comment by achabdo** [comment]
@StevenArzt  thank you for the explanation, there are no other solution rather using ignore-wrong-staticness:true?

**Comment by mbenz89** [comment]
@StevenArzt Thanks for the detailed explanation!

**Comment by StevenArzt** [comment]
There is also a mode that attempts to fix the staticness instead of ignoring it. You can have a look at the "wrong-staticness" parameter, it supports a value "fix".

**Comment by achabdo** [comment]
@StevenArzt  do you mean the Options.v().setPhaseOption("jb.tr", "ignore-wrong-staticness:fix"); it does not work to?have the same probleme .I guess there is no issue.

**Comment by mbenz89** [comment]
@achabdo Did that help?

**Comment by achabdo** [comment]
@mbenz89 the solution was to upgrade to the latest soot release and it solved my probleme.
