### ISSUE TITLE
[Question] Self-included libraries when output an apk ?

### ISSUE THREAD

**Issue by Jacoppy** [Sable/soot#1037]
Hello again, 
I am instrumenting an Android application and I am looking deeply in which are the libraries at the end of the process.
I have discovered that there are a lot of extra libraries:

- "org.xml"

- "org.apache"

- "org.w3c"

- "sun."

- "dagger."

It seems also that it loads some facebook libraries . Can you confirm me this? Otherwise there are some libraries which are not correctly extracted by apktool / baksmali that Soot can see.
Thank you again :)

**Comment by mbenz89** [comment]
How could I confirm without having the apk at hand?
Soot is not adding any libraries to an apk which are not on its classpath. Since the JDK is on the classpath by default, there might be some classes from that additionally packed to an apk. There shouldn't be any third party libraries added without explicitly putting them on the classpath, though.

**Comment by Jacoppy** [comment]
Ok perfect thank you :)
