### ISSUE TITLE
Use soot as a library and read the in memory java bytecode representation?

### ISSUE THREAD

**Issue by helloguo** [Sable/soot#1208]
Hi,

I'm not sure if this is the right place to ask this question. Suppose I have some java bytecode in memory stored as an array of byte `byte[]`, can I use soot as a library and feed the in memory java bytecode `byte[]` to soot, and optimize it from there? Any suggestion/pointer/example is much appreciated.

**Comment by ericbodden** [comment]
Hello.

I am afraid all I can tell you is that I myself attempted this years ago and failed. I suppose you desire to run Soot as part of an instrumentation agent. The problem is, though, that to process some class, Soot needs to be able to load its dependent classes. That, then, can heavily interfere with the class loading of the program into which you are inserting the agent.

In the end I decided to stick to ASM instead, although it was less convenient than Soot would have been.

Best wishes
Eric

**Comment by helloguo** [comment]
@ericbodden Thanks for sharing your experience. It's good to know the potential technical challenge to achieve this.

**Comment by ericbodden** [comment]
Hi @helloguo. Actually we are now having some use case for this ourselves. Hence I wonder whether you got anywhere with this... Do you happen to have an implementation of this feature? /cc @piskachev

**Comment by helloguo** [comment]
@ericbodden I didn't implement this feature.

**Comment by ericbodden** [comment]
Too bad, thanks for the info!
