### ISSUE TITLE
Where can I find “How to use Soot API“？

### ISSUE THREAD

**Issue by 0range228** [Sable/soot#1347]
I'm new to Soot,I really want to know how to use Soot's inside API.

Such as `Scene.v()`,for example.

And where can I find examples which used Soot's API, I really want to make progress,quickly.

If anyone knows, Please tell me...Thanks a lot!

**Comment by mbenz89** [comment]
Unfortunately, there is no up-to-date documentation on Soot's highlevel API. [This](https://github.com/Sable/soot/wiki/Fundamental-Soot-objects) and [this](https://github.com/Sable/soot/wiki/Packs-and-phases-in-Soot) some explanation on some of Soots build blocks. The wiki, in general, contains quite some hints while being rather outdated.

Otherwise, I would suggest you have a look at how [other clients](https://github.com/Sable/soot/wiki/Users-of-Soot) use Soot and consider the [test setup](https://github.com/Sable/soot/blob/master/src/systemTest/java/soot/testing/framework/AbstractTestingFramework.java).
