### ISSUE TITLE
Soot just support  to Android API 17?

### ISSUE THREAD

**Issue by WangYeOtw** [Sable/soot#347]
android demo:
targetSdkVersion="18" minSdkVersion="8"

While i use api 18 android.jar to analysis this demo,i found it didn't enter my class(public class MyBodyTransformer extends BodyTransformer), and if i use soot to genarater jimple, it failed, noting out put in sootOutput. 

So i wonder if soot just support to Android API 17?

**Comment by ericbodden** [comment]
No soot supports all API versions. But I don't understand your problem. What demo do you mean? What results are you expecting, which are you getting? If you want help you need to be much more specific. We can't read your brain :-)

**Comment by WangYeOtw** [comment]
Oh,I'm sorry  for my poor English, my problem like this:

I have a project extends from soot, in which, i defined a class:
    public class MyBodyTransformer extends BodyTransformer{
             do somthing ......
    }

And i have use this project analysed many Android APKs. However,I found a problem,
while the analysed  Android APK(HelloWorld.apk)  AndroidManifest.xml  like this: 
    <uses-sdk android:minSdkVersion="8"  android:targetSdkVersion="18" />

At this time, soot use Android API 18 android.jar to do this analysis, but i found my problem didn't enter
 MyBodyTransformer class.

So, I did another test:
java -Xss50m -Xmx2g -cp .\soot.jar;.\AXMLPrinter2.jar;.\;baksmail.jar soot.Main -android-jars E:\soot-test\android-platforms-master  -f jimple -src-prec apk -ire -process-dir E\soot-test\HelloWorld.apk

Usually, while this execution is completed, it will generate all jimple files under "sootOutput" directory,
but this time ,no file generated under "sootOutput" .

So, I wonder if soot just support to Android API 17 now?

**Comment by StevenArzt** [comment]
From your command-line, it looks like you are using the Android platforms from the Sable repository at https://github.com/Sable/android-platforms. The newest version in there is actually Android API revision 17, so Soot will complain if you are trying to analyze any newer apps, but only have those JARs.

In general, there are only very limited cases in which you need these JARs. In most cases, it is better to use the JARs shipped with the normal Android SDK. You can find them in the "platforms" folder inside your SDK directory. The difference is that the Sable JARs are complete implementations extracted from emulators or phones, whereas the ones shipped with the Android SDKs are stubs. The stubs do not contain any real implementations, but every method just throws a NotImplementedException which is totally sufficient if you analysis needs nothing but the correct signatures of the Android library methods. Only if you create an analysis that analyzes the internal workings of the Android operating system, you need the full JARs. Otherwise, they are only considerably slowing down your analysis and eating up your memory and you're much better off with the stubs from the Android SDK.

**Comment by WangYeOtw** [comment]
Oh ,I get it, Thanks for your answers,ericbodden,StevenArzt.
