### ISSUE TITLE
Commit f7bf9fc0861867230e72b8405f47bd9f09c13e62 is incomplete

### ISSUE THREAD

**Issue by bergerbd** [Sable/soot#371]
Commit f7bf9fc0861867230e72b8405f47bd9f09c13e62 deletes old libraries and introduces new ones but they are not added to the repository.

**Comment by ericbodden** [comment]
This might also explain why the abc build failed last night...

**Comment by StevenArzt** [comment]
I added the missing libraries.

The real ABC build did not really fail - the e-mail that you got was from the old build vandyk machine which has been scheduled to eventually go out of order for quite a while now. The real productive builds have long since moved to ssebuild.cased.de which works perfectly fine. The new machine does not depend on the checked-in libraries, but compiles dexlib and takes the JARs from there. This has the advantage of always giving us the most up-to-date dexlib with all bugfixes. The same build principle applies to all builds there: We build everything we need and put it in an artifact archive. Every project that needs a library pulls the newest stable version out of the archive. This also enables us to see whether changes in one library broke something in another library that uses the first one.

**Comment by bergerbd** [comment]
ant.settings.template still references the old libraries.

**Comment by StevenArzt** [comment]
Fixed.

**Comment by bergerbd** [comment]
Is fixed.
