### ISSUE TITLE
Error: Could not find or load main class soot.Main

### ISSUE THREAD

**Issue by OxfordNJ** [Sable/soot#629]
I have a simple question:(under Linux system)
My command is(in Terminal):
java -cp soot-2.5.0.jar soot.Main
But i get an error:
Could not find or load main class soot.Main
What happened with it? Can anybody give me a help?
(My environment variable has been settled properly. )

**Comment by Tracy6465** [comment]
have you solved the  problem?

**Comment by suvamM** [comment]
Hi,

This is probably because Java could not find the Soot jar file. Try the following:

java -cp <complete-path-to-soot.jar> soot.Main

For example, if your soot-2.5.0.jar is located at /home/oxford/soot-2.5.0.jar, then your command should be

java -cp /home/oxford/soot-2.5.0.jar soot.Main

If you are in the same directory as the jar, you need not prepend the path, and your original command should work. Hope that helps.

**Comment by pengzhendong** [comment]
Command:
1. java -cp jasminclasses-2.5.0.jar:polyglotclasses-1.3.5.jar:sootclasses-2.5.0.jar soot.Main --help
2. java -cp sootclasses-2.5.0.jar soot.Main 
Result: 
1. Error: Could not fimd or load ...
2. It works.

# Why

**Comment by anddann** [comment]
Works with release 4.0
