### ISSUE TITLE
Maintenance of application, library, and phantom class sets by Scene

### ISSUE THREAD

**Issue by gbalats** [Sable/soot#673]
I'm trying to understand the handling of application, library, and phantom classes by Scene.

Specifically, what I'm trying to achieve, is to ensure that the `activeHierarchy` of scene is not modified, when adding phantom classes. This, after all, seems to be the intended behavior (according to the documentation and comments; see below).

To that end, I have found what is causing the current behavior, which is to modify the hierarchy every time (even in the case of phantom classes). I can provide a fix, but I first want to understand the code a little better.

1. Scene maintains 4 sets of classes: (i) `applicationClasses` , (ii) `libraryClasses`, (iii) `phantomClasses`, (iv) and `classes`. Is the last one (i.e., `classes`) intended to be a superset of all the other 3 sets?

    If so, this does not seem to be properly enforced via `SootClass`'s respective setter methods that may add a class to, let's say the library class subset, even if it's not included in `classes`.

2. Also, there is the `isPhantom` boolean field of `SootClass`. How does this relate to the `phantomClasses` set maintained by `Scene`? Is it to allow a library or application class be marked as phantom, or is there some other kind of invariant?

    What does it mean, for a class, to have `isPhantom` set to true but to not be included in `phantomClasses`? Is the opposite possible?

3. There are also 2 similar methods `SootClass.setPhantomClass()` and `SootClass.setPhantom(boolean)`, where the documentation of the 2nd one states:

    > Marks this class as phantom, without notifying the Scene.

    However, this isn't what actually happens, since calling `setPhantom(true)` will call `setPhantomClass()` and add it to the `phantomClasses` set (and also set its `isPhantom` field).

    There seems to be an error on either the documentation or in the `setPhantom()` method, but I'm not sure which.

4. With the previous point in mind, the `Scene.getSootClassUnsafe()`, when adding a phantom class, does the following:
    ```
    963     SootClass c = new SootClass(className);
    964     addClass(c); 
    965     c.setPhantom(true);
    ```

    Calling `Scene.addClass()` though will instantly add the given class to the library class set of `Scene` and thus always (needlessly as it seems) modify the hierarchy (since the condition `!c.isPhantom` will always evaluate to true): 

    ```
    691     classes.add(c);
    692     c.setLibraryClass();
               ...
    698     // Phantom classes are not really part of the hierarchy anyway, so
    699     // we can keep the old one
    700     if (!c.isPhantom)
    701         modifyHierarchy();
    ```
    Swapping the `addClass(c)` and `c.setPhantom(true)` instructions doesn't work, since `addClass()` will unconditionally clear the `isPhantom` field and mark `c` as a library class, regardless.

    The comment suggests that the hierarchy doesn't need to change when adding phantom classes, which is not what happens. Why does `addClass()` need to mark the class to be added, as a library class?

**Comment by StevenArzt** [comment]
Soot's concept of classes is a bit difficult, but your idea looks right. All classes are loaded into the Scene, so Scene.getClasses() gives you all classes that your current Soot instance has heard of. Such classes can either be application classes (all stuff that comes from the process-dir) or a library class (all stuff that comes from the soot classpath). A class is a phantom if it was not found by Soot's class resolver when it was requested. So the "classes" are the superset of application classes, library classes, and phantom classes.

Adding classes to the Scene is normally the duty of the resolver. The setters for changing a class from a library class to an application class and vice versa only make sure that the respective sets are maintained. They are not responsible for enforcing invariants on the Scene as a whole. A non-faulty resolver will always add the class to the Scene, which adds it to "classes".

The "phantomClasses" set and "isPhantom" should normally be in sync. The main reason that we keep the extra set around is to have a quick access to all phantom classes without having to iterate over all classes in "classes" and check "isPhantom" for every class. I'm not sure that this is actually a common use case, so we might chose to drop the set in the future. If the flag and the set are out of sync, that's definitely a bug and one more reason for dropping the set.

The reason why addClass() marks the new class as a library class is that library classes are the default. Everything that shall be an application class must be marked as such explicitly. This is all not very nice, but it's hard to change anything there without breaking backwards compatibility in most likely complety unexpected ways.

Still, adding a phantom class to the Scene should not invalidate the hierarchy. To sort this out, I did the following:

(1) There is a new method Scene.addClassSilent() for adding a class to the Scene without marking it as a library class and without invalidating the hierarchy.
(2) The behavior of Scene.addClass() remains unchanged, but I added a Javadoc comment.
(3) When creating a phantom class in Scene.getSootClassUnsafe(), we now use addClassSilent().

This should at least solve the problem at hand. I removed the setPhantom(boolean) method, because it doesn't do what one would expect from the Javadoc and for what it actually does, we already have setPhantomClass(). I hope that not too many things break.

**Comment by gbalats** [comment]
I think this doesn't solve the problem yet, since `Scene.getSootClassUnsafe()` will call `setPhantomClass()` only after calling `addClassSilent()`. Hence, the latter will still modify the hierarchy.

I submitted a pull request with a quick fix that just sets the `isPhantom` field of the class, before calling `addClassSilent()`. This should prohibit any hierarchy modification at this point.
