### ISSUE TITLE
Jimple to Java

### ISSUE THREAD

**Issue by gaoxiang9430** [Sable/soot#740]
Soot can generate a dummy main method. I find that the dummy main method is jimple language based. Is it possible to convert the jimple program to java program? If possible, could please give me some suggestions?

**Comment by anddann** [comment]
You can write out the jimple code to a `.class` file as explained in the documentation https://github.com/Sable/soot/wiki/Creating-a-class-from-scratch#write-to-class-file

**Comment by alessiogambi** [comment]
Hi @anddann, 
I am following your suggestion to generate .class from .jimple, but in different occasions the .class that I generate triggers an exception as follow:

`Exception in thread "main" java.lang.VerifyError: (class: org/employee/TestFileRead2_2, method: test_87 signature: ()V) Expecting to find object/array on stack`

ATM, I workaround this by decompiling the .class into a .java and recompiling the .java back to .class

**Comment by anddann** [comment]
Can you give an example where the jimple to class generation fails?

**Comment by alessiogambi** [comment]
Apologies for the delay. It turned was my fault, I passed the wrong type of argument for the  method calls I generated. Things like, `print(Object)`  instead of `print(int)`. I assumed that Soot would complain in such cases, but it did not (or I did not see). 

Anyway, it would be really nice to automagically output Java source code.
