### ISSUE TITLE
Analysis Android SDK with Soot

### ISSUE THREAD

**Issue by lczxxx123** [Sable/soot#771]
Hi，I'm trying to analysis androidSDK with Soot.
But i realize that androidSDK doesn't have a main method, so how can i get something like CallGraph to help me analysis androidSDK?

Any pointer will be helpful. 
Thanks in advance.

**Comment by mbenz89** [comment]
Hi.

To generate a call graph for the the SDK, you basically have to generate a method calling all public APIs. This will be your main method.
Since you do not want to imply an order of API invocations during call graph generation, it would be a good idea to enclose all of this in a while loop.
For further reading, I suggest having a look at the main method generation used in FlowDroid (soot-infoflow-android).

Manuel
