### ISSUE TITLE
Remove Ant completely

### ISSUE THREAD

**Issue by jpstotz** [Sable/soot#797]
Currently Soot is an plain Eclipse project and additionally it also tries to be a Maven project as well. 

Having both at the same time is a simple way to confuse developers as everything has to declared twice.

As most Eclipse versions already include the M2Eclipse (Maven for Eclipse support) there is a simple alternative:

Convert it to an Eclipse Maven project, remove the project and local dependencies (jars from lib folder).
Instead manager everything via `pom.xml`. 

One minor advantage is that you can open Soot in Eclipse without having ***heros*** and ***jasmin*** checked-out as project as it is automatically resolved by Maven.

**Comment by mbenz89** [comment]
This eclipse project file is a relict from pre maven times. 
Unfortunately, I do not use eclipse and thus cannot provide an updated version of the file. You are welcome to provide a pull request for that if you like.

On the other hand, isn't it sufficient to do something like 'import existing maven project' to get the correct setup? What would be the benefit of an eclipse maven project file over having none?

**Comment by jpstotz** [comment]
Well that explains why your commits don't correct the missing libraries in the Eclipse project config.
As long as an Eclipse project configuration exists one does not expect that it is unmaintained and broken.

Anyway I thought Soot is bound to Eclipse (and therefor all maintainers use Eclipse) especially because of the Soot Eclipse plugin source code that should AFAIR be hidden somewhere within Soot (and that IMHO should be moved to a sub-project like the soot-cli interface).

From my perspective the Soot project requires some clean-up: 
1. There are a lot of Apache Ant tasks. Some of them has been replaced by Maven but who knows what is necessary wand what is outdated junk? Do they work anymore or is it better to remove them? Be careful: I have not checked it in detail but it looks like the Ant script (partly) depends on the libraries from the `libs` folder. This part works totally independent from Maven.

2. The Eclipse project files. IMHO if they are not maintained they should be removed because outdated and non-working project files are always causing trouble. I an not sure how good the import of a Maven project files works in Eclipse - especially as the project structure is anything but Maven compliant (I just say src/main/java)...

**Comment by ericbodden** [comment]
Soot itself has never dependent on Soot and we should please avoid such dependencies in the future. It would be ok if the usage of eclipse were only optional.

Cheers
Eric

--
Sent via my mobile

On Oct 20, 2017 16:43, "Jan S." <notifications@github.com> wrote:

Well that explains why your commits don't correct the missing libraries in the Eclipse project config.
As long as an Eclipse project configuration exists one does not expect that it is unmaintained and broken.

Anyway I thought Soot is bound to Eclipse (and therefor all maintainers use Eclipse) especially because of the Soot Eclipse plugin source code that should AFAIR be hidden somewhere within Soot (and that IMHO should be moved to a sub-project like the soot-cli interface).

From my perspective the Soot project requires some clean-up:

  1.  There are a lot of Apache Ant tasks. Some of them has been replaced by Maven but who knows what is necessary wand what is outdated junk? Do they work anymore or is it better to remove them? Be careful: I have not checked it in detail but it looks like the Ant script (partly) depends on the libraries from the libs folder. This part works totally independent from Maven.

  2.  The Eclipse project files. IMHO if they are not maintained they should be removed because outdated and non-working project files are always causing trouble. I an not sure how good the import of a Maven project files works in Eclipse - especially as the project structure is anything but Maven compliant (I just say src/main/java)...

**Comment by mbenz89** [comment]
I agree to remove the eclipse project file, it is just another configuration to be kept updated and doesn't give much value.

Regarding Ant, it should still be working as well as the Maven script. We just moved from Ant to Maven and Ant will probably be removed soon. Generally, I agree that having both is confusing and eventually just leads to consistency problems.

Manuel

**Comment by mbenz89** [comment]
@StevenArzt do you agree with removing the eclipse .project and .classpath files? 
I think Soot should be easily addable to eclipse by import as maven.

**Comment by mbenz89** [comment]
Eclipse project files where changed to work with maven instead of local jars: 3e8dced9e5f669a7a247a6ef4ecc6bc7b459da97

**Comment by mbenz89** [comment]
Ant was removed 01036b49361160d0e02c5b484f5247b6351741fb
