### ISSUE TITLE
Which code formatter to use for soot project(s)?

### ISSUE THREAD

**Issue by jpstotz** [Sable/soot#812]
Java is a language that allows automatic formatting. Therefore IMHO refuse to perform manual code formatting - that is dumb work that should be done automatically. 

The problem for an open source software is that we have to agree on one formatter, otherwise commits contain a lot of changes that are only related to code formatting.

Therefore I am asking the Soot community if there is already an agreement on a specific code formatter. May be it is possible to make git apply the code formatter on every commit?

**Comment by ericbodden** [comment]
Hello. I like the idea of git-enabled formatting. @mbenz89 can we maybe have somebody look into this?

**Comment by mbenz89** [comment]
Hi, I agree that we should have a common formatting style to make changes more clear. I'll investigate this myself.

**Comment by ericbodden** [comment]
Something that came to my mind: does this help in cases where others send us pull requests? I guess in this case we have no way to enforce an automatic formatting, have we? I guess this is something they’d have to do on their side. Or does Github have special support for this?

Cheers
Eric

**Comment by mbenz89** [comment]
Generally, we can either do the formatting upstream or downstream. The problem with doing the formatting upstream is that after pushing, the head of your local repository will be behind the upstream repository (since the formatted version of your changes is not in the local repository), requiring a merge on your side. This is error-prone and unintuitive. 

I suggest we firstly agree on a formatting style (I prefer [google's](https://google.github.io/styleguide/javaguide.html) for which there is also [tool support](https://github.com/google/google-java-format) and plugins to all common IDEs) and then propose a git pre-commit hook that does the formatting on each (local) commit. Contributors will then have to register the git hook after cloning and everything else happens automatically. 
If someone misses employing our formatting guidelines for a pr, we can just reject it and ask for appliing the formatting.

Manuel

**Comment by hubertp** [comment]
Hi. Any chance somebody is tackling that one? I would be happy to contribute a bit, but lack of common of style (especially tabs vs spaces, indentation) is a sufficient deterrent for me.
I quickly added checkstyle with google style (available https://github.com/hubertp/soot/tree/hubertp/checkstyle) which runs after `tests` and revealed 531507 violations. The good thing is it is mostly indentation/line size issues because they seem to have been never enforced. The bad thing is it is still ~500000 violations. I wouldn't like to start working on it only to be later told that this is too invasive (and it will be). Yes/no?

**Comment by jpstotz** [comment]
@hubertp I haven't used Checkstyle for a while. Is Checkstyle able to automatically correct simple problems such as formatting problems or do we still need and additional formatter (may be there is a Maven plugin for the google code formatter?).

**Comment by mbenz89** [comment]
Hi everyone.

I'm already working on the integration of checkstyle and Google's code formatter.
I think I'm already down to about 2000 detected code-smells. You are more then welcome if you like to contribute and modify Soot's codebase so that it complies with Google's coding style. You can find the current state in the [codingstyle](https://github.com/sable/soot/tree/codingstyle) branch (still one or two commits behind).

@jpstotz Checkstyle just detects smells but doesn't fix them. Regarding the formatting, one can automatically apply it with Google's code [formatting tool](https://github.com/google/google-java-format) which can either be used with a git pre-commit hook or an IDE plugin to apply it on the fly. Have a look at the "codingstyle" directory in the aforementioned branch.

Best,
Manuel

**Comment by jpstotz** [comment]
Looks nice this branch - thank you Manuel.
I will tell my student to postpone the slf4j adaption as discussed in #401 until this has been merged into the develop branch.

**Comment by hubertp** [comment]
My personal preference is to avoid automatic formatting as a pre-commit hook since it will always end up doing some magic, and the changes may come up as a surprise to the developer. I tend to lean towards having PR build do the check - after all it should be the original commiter's responsibility to ensure the quality of the code and (for example) jenkins should verify that.

And as @mbenz89 noted, checkstyle only checks if the code conforms, it doesn't do any formatting itself.

Whatever really works for you guys, as long as there is some kind of automatic gatekeeper out there to ensure that the code does not deteriorate over time.

**Comment by mbenz89** [comment]
I agree that pre-commit formatting may be a bit unintuitive to some developers. However, using the hook is just an option, not a requirement. As you suggested, the plan is to have the PR builder to check the formatting/style and reject the PR if not compliant. It is the developers choice/responsibility (how) to apply the formatting and ensure his code conforms to our coding style.

It will take some time till we got all those issues resolved. We are also planning some major restructurings of Soot in the future, which will break current clients. Maybe we will deploy those changes together since the necessary changes to conform to Google's coding styles also involves member renamings that might break clients. I would prefer having this rather sooner than later but the decision on this has still to be made.

Manuel

**Comment by mbenz89** [comment]
addressed with #928
