### ISSUE TITLE
SootMethod.getSignature should cache results

### ISSUE THREAD

**Issue by zhuowei** [Sable/soot#915]
I noticed that SootMethod's getSignature method always recalculates the signature; this causes getSubSignatureImpl to be called many times for the same method - it's the most called method in the Sampler trace in VisualVM in an application I'm debugging.

Would caching the result of getSignature help increase performance?

**Comment by StevenArzt** [comment]
Soot recalculathe signature, because as a compiler framework, it was built for transformations. This means that Soot is based on the assumption that everything can change at any time. This assumption may seem strange when using Soot purely for analyses, but makes sense in a compiler. Going forward, it would make sense to have some sort of cache, which automatically gets invalidated when something (e.g., the method name or the name of the declaring class) changes,

**Comment by mbenz89** [comment]
We are working on this for an upcoming release. For the time being, we have to cope with these assumptions.
