### ISSUE TITLE
Maybe a bug in wiki

### ISSUE THREAD

**Issue by spyyes** [Sable/soot#917]
In the wiki <Introduction: Soot as a command line tool>, I nocited that there maybe a bug..
\
When using parameter `-pp` for classpath declaration, the command order `java -cp sootclasses-trunk-jar-with-dependencies.jar -cp . -pp A B` cannot run on my computer, which says "Unrecognized option: -pp ".
\
Instead, I think it's okay to use `java -jar sootclasses-trunk-jar-with-dependencies.jar -cp . -pp A B`

**Comment by mbenz89** [comment]
Thanks for reporting!

**Comment by anddann** [comment]
The error `Unrecognized option`is thrown by the JVM itself but not by soot.
The JVM expects the class to execute as an argument, thus
we can write ` java -jar sootclasses-trunk-jar-with-dependencies.jar -cp . -pp A ` as suggested or simply provide soot's main class using `java -cp sootclasses-trunk-jar-with-dependencies.jar soot.Main -cp . -pp A`.
Both works, but the first solution requires a main class declared in the jar's manifest.
Anyway, I added the second cmd option to the wiki in order to be consistent with the rest.
