### ISSUE TITLE
Continuous build system

### ISSUE THREAD

**Issue by ericbodden** [Sable/soot#94]
We currently use Jenkins for continuous integration. The build server thereby proceeds as described at the bottom of this page:

http://www.bodden.de/clara/downloads/

We should clean up this process such that Soot and its dependencies are all clear and modeled the same way and such that we have some unified build process. This may mean switching to something like Maven or Gradle or similar. 

see #44

**Comment by StevenArzt** [comment]
Since this is pretty much a copy of #44 and we have now splitted the various components on the build server, I close this issue. The current status is: We build Jasmin, Heros, Soot, and ABC all on their own. Only those builds that succeed and for which the test cases (if any) run without issues are archived. The archived files are then on one hand available on the web through our nightly build site and on the other hand are used if another project has dependencies. This means that the Soot build for instance fetches the last stable Jasmin build. We achieve this with Jenkins' artifact archival function which is totally sufficient for the nightly build server. More general dependency discussions should be done in #44.
