### ISSUE TITLE
“int" to "byte" after transforming to Jimple by mistake

### ISSUE THREAD

**Issue by Nebula010** [Sable/soot#973]
Sometimes there is a variable _x_ declared to be a _int_ in .java: 

_int x = 0;_

After transforming to .jimple, it becomes a _byte_ instead:

_byte x;_
......
......
_x = 0;_

How to maintain a variable's original type when transforming...?

**Comment by mbenz89** [comment]
During type inference, Soot's Type Assigner (jb.tr phase) uses the most narrow type possible. You can try to use the old type assigner, it might not implement the same optimization.
No guarantees, though.

Since Soot infers `x` to be of type byte, x shouldn't be used in a context where byte is inappropriate. Why does this render a problem for you?

**Comment by Nebula010** [comment]
Thank you very much. I am using Soot for instrumenting a Java program, and I noticed that I did not get the output of x when I tried to get all the integer values.
